### ISSUE TITLE
Are multiple requesters with one responder supported?

### ISSUE THREAD

**Issue by paoloc0** [awslabs/amazon-sqs-java-temporary-queues-client#27]
Hi. My use case is: I'd like to implement a request-response system via SQS, and have a single responder handling requests from multiple requesters (without having to create a new SQS queue/queues for every requester, every time I add one). Is this something that is envisioned (or already possible) for amazon-sqs-java-temporary-queues-client?

Thanks

**Comment by robin-aws** [comment]
That should be a great use case for this library! When you say "multiple requesters", does that mean multiple individual requests at a time, or multiple client processes that will each send multiple requests over their lifetime?

The library does create a single shared response queue for each requesting client, which is necessary to make sure responses are received by the client that sent the request. It specifically avoids creating a response queue per request though - it uses virtual queues hosted by the single response queue per-client instead.

**Comment by paoloc0** [comment]
Hi. I meant the latter: multiple client processes that will each send multiple requests over their lifetime. I realise that the library already avoids creating a response queue per request.

This would be a great feature. I'm not sure what other peoples' use cases look like, but this would be the typical pattern for me: deploying some service, and then adding multiple consumers of the service over time.

**Comment by codemepat** [comment]
Hi Robin - I'm working on similar use case wherein multiple client requestors will send SQS message to same queue handled by responder running as a lambda in cloud. This responder will send responses back to their corresponding requestors.

From your comment above, it seems like this behavior is supported in the current released library. Can you confirm that? @paoloc0 commented above to add a request for this feature. May be I'm missing something that is not apparently clear!

**Comment by robin-aws** [comment]
Correct, and that is one of the prime use cases for the library! Each client requestor will create their own dedicated response queue, and the responder will send responses to the appropriate response queue.

**Comment by paoloc0** [comment]
@robin-aws Ok, it seems I misunderstood you. But just to be clear: when I said "multiple requesters", I meant "multiple requesters running on multiple JVMs". So, as I understand it now:

- the answer to the original question "Are multiple requesters [from multiple JVMs] with one responder supported?" is "yes";
-  multiple such requestors can all send requests to a single SQS request queue (although a queue per requestor is created, for responses to be sent to).

Presuming the above is correct: I would imagine that each client requestor (which is on its own JVM) must use a unique `internalQueuePrefix` to avoid stomping on other client requestors - is that right? The documentation seems to say the opposite, but I'm not sure if the word "clients" below means "clients running within one JVM" or "clients running across multiple JVMs":

> The background thread uses the ListQueues and ListTags API actions to check all queues with the configured prefix, deleting any queues that haven't been tagged for at least five minutes. In this way, if one client doesn't shut down cleanly, the other active clients clean up after it. In order to reduce the duplication of work, all clients with the same prefix communicate through an shared, internal work queue named after the prefix.

**Comment by robin-aws** [comment]
Each instance of the client (whether in the same JVM or not) will generate a UUID and append it to the `internalQueuePrefix`, so that ensures there's no cross-talk between requestors. The common prefix is used by the temporary queue sweeping process, so that it can only sweep the subset of queues in an account that might need to be reaped.

**Comment by paoloc0** [comment]
Great, thanks. Seems like all the functionality I was hoping to use is already supported.
