### ISSUE TITLE
NPE when short-polling a virtual queue

### ISSUE THREAD

**Issue by robin-aws** [awslabs/amazon-sqs-java-temporary-queues-client#4]

**Comment by kmbotts** [comment]
I ran into this myself. Appears that the ReceiveMessageRequest.waitTimeSeconds is type Integer, so it will be null if not provided. The Completable future get timeout seconds is long type. So the NPE is a result of the auto-boxing of Integer to long which isn't clear as it's happening under the hood in the JVM.
