### ISSUE TITLE
Orphaned message warnings

### ISSUE THREAD

**Issue by codemepat** [awslabs/amazon-sqs-java-temporary-queues-client#56]
We are observing excessive orphaned message warnings like below. I have grabbed these logs when there are no application activities happening, i.e. application is idle not servicing any request/response SQS related traffic during this period.
"com.amazonaws.services.sqs.AmazonSQSVirtualQueuesClient","message":"Orphaned message sent to __RequesterClientQueues__f
4ec3578-16ea-4206-9675-f11ccd910732: 0d580fc2-e160-4033-b593-5dc3121a7871","endOfBatch":true,"parameterCount":0,"formattedMessage":"Orphaned message sent to __RequesterClientQueues__f4ec3578-16ea-4206-9675-f11ccd910
732: 0d580fc2-e160-4033-b593-5dc3121a7871","loggerFqcn":"org.apache.commons.logging.impl.SLF4JLocationAwareLog","threadPriority":5,"threadId":128,"}

In one hour idle period, 905 orphaned msgs were observed on one deployment system, and 1021 orphaned msgs on second deployment system. These behavior is consistent observed since our production launch couple of weeks back.

In certain cases, we have observed these messages lead to SQS request throttling errors. Our system is ramping up traffic in production and would like to understand root cause of this errors as well as any potential issues with request throttling.

**Comment by adam-aws** [comment]
Hi,

An Orphaned message means a virtual queue has been deleted but a message is still being sent to it, a warning will be logged stating that the message has been orphaned (note: this message handler can be customized). What could cause a message to be orphaned:

* Response client took too long to respond and the virtual queue got deleted in the meantime.
* A small idle queue retention period could cause the virtual queue to be deleted prematurely.
* Creating multiple `AmazonSQSRequester` using the same internal queue prefix (by default it is `__RequesterClientQueues__`). The Host queues get deleted and we start seeing an excessive amount of Orphaned messages. Setting a different internal queue prefix resolves the issue.

I believe the 3rd case is likely why you are seeing excessive warnings about Orphaned messages. Using a different internal queue prefix for each `AmazonSQSRequester` should reduce those warnings.

Will keep this issue open in case this does not reduce the number of warnings received.

**Comment by yzhang-okta** [comment]
> Hi,
> 
> An Orphaned message means a virtual queue has been deleted but a message is still being sent to it, a warning will be logged stating that the message has been orphaned (note: this message handler can be customized). What could cause a message to be orphaned:
> 
> * Response client took too long to respond and the virtual queue got deleted in the meantime.
> * A small idle queue retention period could cause the virtual queue to be deleted prematurely.
> * Creating multiple `AmazonSQSRequester` using the same internal queue prefix (by default it is `__RequesterClientQueues__`). The Host queues get deleted and we start seeing an excessive amount of Orphaned messages. Setting a different internal queue prefix resolves the issue.
> 
> I believe the 3rd case is likely why you are seeing excessive warnings about Orphaned messages. Using a different internal queue prefix for each `AmazonSQSRequester` should reduce those warnings.
> 
> Will keep this issue open in case this does not reduce the number of warnings received.

If we're using a different internal queue prefix for each AmazonSQSRequester, how could I set for `AmazonSQSResponder`withInternalQueuePrefix ?
